# Generated by Django 3.1.1 on 2020-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Cliente')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del cliente', max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Ingrese el apellido del cliente', max_length=200, verbose_name='Apellido')),
                ('telefono', models.IntegerField(help_text='Ingrese el numero de telefono', verbose_name='Telefono')),
                ('calle', models.CharField(help_text='Ingrese la calle', max_length=200, verbose_name='Calle')),
                ('ciudad', models.CharField(help_text='Ingrese la ciudad', max_length=200, verbose_name='Ciudad')),
                ('numero', models.CharField(help_text='Ingrese el numero de la vivienda', max_length=200, verbose_name='Numero')),
                ('pais', models.CharField(help_text='Ingrese el pais', max_length=200, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['-id'],
            },
        ),
    ]
