# Generated by Django 3.1.1 on 2020-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='calle',
            field=models.CharField(default='Tressens', help_text='Ingrese la calle', max_length=200, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='ciudad',
            field=models.CharField(default='Calderón', help_text='Ingrese la ciudad', max_length=200, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='numero',
            field=models.CharField(default='S/N', help_text='Ingrese el numero de la vivienda', max_length=200, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='pais',
            field=models.CharField(choices=[('1', 'Argentina'), ('2', 'Chile'), ('3', 'Uruguay'), ('4', 'Bolivia')], default='Argentina', help_text='Seleccione el pais (agregue opciones para evitar posibles errores en el tipeo)', max_length=200, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(help_text='Ingrese el numero de telefono', max_length=200, verbose_name='Telefono'),
        ),
    ]
