# Generated by Django 3.1.1 on 2020-09-21 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0003_auto_20200921_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-id'], 'permissions': (('asignar', 'Asignar usuarios que pueden ver la plantilla'),), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Formularios'},
        ),
        migrations.AlterField(
            model_name='formulario',
            name='permiso',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
