# Generated by Django 3.1.1 on 2020-09-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_auto_20200921_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-id'], 'permissions': (('asignar', 'Asignar usuarios con acceso'),), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Formularios'},
        ),
        migrations.AddField(
            model_name='formulario',
            name='address',
            field=models.CharField(default='S/A', max_length=200, verbose_name='Address'),
        ),
    ]
