# Generated by Django 3.1.1 on 2020-09-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_auto_20200922_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='address',
            field=models.CharField(default='Tressens, Calderón, Argentina', help_text='Se autocompleta con los datos ingresados arriba', max_length=200, verbose_name='Dirección(se autocompleta)'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='calle',
            field=models.CharField(default='Tressens', max_length=200, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='ciudad',
            field=models.CharField(default='Calderón', max_length=200, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='numero',
            field=models.CharField(blank=True, default='S/N', max_length=200, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='pais',
            field=models.CharField(default='Argentina', max_length=200, verbose_name='Pais'),
        ),
    ]
