# Generated by Django 3.1.1 on 2020-09-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_auto_20200922_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='numero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero'),
        ),
    ]
